# Generated by Django 3.2.25 on 2025-01-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='operacao',
        ),
        migrations.AddField(
            model_name='atividade',
            name='nome',
            field=models.CharField(default='Atividade Padrão', max_length=255),
        ),
        migrations.AddField(
            model_name='atividade',
            name='operacoes',
            field=models.ManyToManyField(blank=True, to='core.Operacao'),
        ),
    ]
