# Generated by Django 3.2.25 on 2025-01-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250124_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.PositiveBigIntegerField(blank=True, default=0)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atividade')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operacao')),
            ],
        ),
    ]
