# Generated by Django 3.2.25 on 2025-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250205_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='tempo_total',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
