# Generated by Django 3.2.25 on 2025-02-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atividade_tempo_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='operacao',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classificacao'),
        ),
    ]
