# Generated by Django 3.2.25 on 2025-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250206_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='operacoes',
            field=models.ManyToManyField(related_name='maquinas', to='core.Operacao'),
        ),
    ]
