# Generated by Django 3.2.25 on 2025-03-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_maquina_operacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade_Py',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Atividade Padrão', max_length=255)),
                ('data_hora_inicio', models.TextField()),
                ('data_hora_fim', models.TextField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('tempo_total', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao_Py',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao_Py',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classificacao_py')),
            ],
        ),
        migrations.CreateModel(
            name='PostoTrabalho_Py',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tempos_Py',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.PositiveBigIntegerField(blank=True, default=0)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atividade_py')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operacao_py')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina_Py',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('operacoes', models.ManyToManyField(related_name='maquinas', to='core.Operacao_Py')),
            ],
        ),
        migrations.AddField(
            model_name='atividade_py',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maquina_py'),
        ),
        migrations.AddField(
            model_name='atividade_py',
            name='posto_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postotrabalho_py'),
        ),
    ]
